services:
  - type: web
    name: nail-salon
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run server
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: LINE_NOTIFY_TOKEN
        sync: false
      - key: PORT
        value: 4000